### PR TITLE
Auto-generated Schema for Edge

### PR DESCRIPTION
**Pull request by marcusgrando**
Auto-generated Schema for Edge

### CODE REVIEW

**Comment by marcusgrando** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by marcusgrando** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by marcusgrando** [comment]
I have read the CLA Document and I here by sign the CLA

**Comment by marcusgrando** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ricardojrabreu** [comment]
I have read the CLA Document and I here by sign the CLA

**Review by trgalho — APPROVED** [review]

**Review by AlessandroSFreitas — APPROVED** [review]

**Pull request merged**
