### PR TITLE
[ENG-26328] fix: add description field on examples and patch endpoint

### PR DESCRIPTION
**Pull request by AlessandroSFreitas**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by AlessandroSFreitas** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by GuilhermeScherner — APPROVED** [review]

**Comment by AlessandroSFreitas** [comment]
recheck

**Review by rogerclaus — DISMISSED** [review]

**Comment by tiagokrebs** [comment]
recheck

**Comment by AlessandroSFreitas** [comment]
recheck

**Comment by AlessandroSFreitas** [comment]
recheck

**Pull request closed without merging**
